### Example of frontend creating request to the backend

POST  https://sheltered-escarpment-12995.herokuapp.com/api/contact/message
content-type: application/json

{
    "name": "heroku test",
    "email": "deepgrg03@gmail.com",
    "subject": "",
    "message": "validating input"
}

### 
