### Example of frontend creating request to the backend

POST  http://localhost:8000/api/contact/message
content-type: application/json

{
    "name": "mongodb test",
    "email": "deepgrg03@gmail.com",
    "subject": "",
    "message": "validating input"
}

### 
